const Menu = [{
        id: 1,
        image: "https://i1.wp.com/vegecravings.com/wp-content/uploads/2020/01/Vegetable-Masala-Maggi-Recipe-Step-By-Step-Instructions-scaled.jpg?resize=1024%2C900&quality=65&strip=all&ssl=1",
        name: "Maggi",
        price: "12rs",
        category: "Breakfast",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, dignissimos.",
    },
    {
        id: 2,
        image: "https://i2.wp.com/vegecravings.com/wp-content/uploads/2021/02/Onion-Pakora-Recipe-Step-By-Step-Instructions-scaled.jpg?resize=2048%2C1552&quality=65&strip=all&ssl=1",
        name: "Pakora",
        price: "20rs",
        category: "Evening",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, dignisscimos.",
    },
    {
        id: 3,
        image: "http://maunikagowardhan.co.uk/wp-content/uploads/2011/11/Chilli-Paneer-1024x683.jpg",
        name: "Chilly paneer",
        price: "120rs",
        category: "Lunch",
        description: "Lorem ipsum dolor sit amet consecterrtur adipisicing elit. Odit, dignissimos.",
    },
    {
        id: 4,
        image: "https://embed.widencdn.net/img/mccormick/mjdxosbfzz/2000x1125px/HYDERABADI-BIRYANI.jpg?crop=true&anchor=0,0&q=80&color=ffffffff&u=qwwekl",
        name: "Biryani",
        price: "202rs",
        category: "Dinner",
        description: "Lorem ipsum dolor sit amet cggonsectetur adipisicing elit. Odit, dignissimos.",
    },
    {
        id: 5,
        image: "https://d1uz88p17r663j.cloudfront.net/resized/24c301e2f24e80617c1f0bd54b768650_Step_3_744_419.png",
        name: "Fried rice",
        price: "90rs",
        category: "Lunch",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, dignissimos.",
    },
    {
        id: 6,
        image: "https://www.thespruceeats.com/thmb/O4xB3FoR7B6ovTpcENFLtQyIuAU=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/indian-style-burger-1957599-hero-01-266103a4bb4e4ee7b5feb4da2d2e99da.jpg",
        name: "Burger",
        price: "110rs",
        category: "Evening",
        description: "Lorem ipsum dolor sit amet consectetur adipisihgbbcing elit. Odit, dignissimos.",
    },
    {
        id: 7,
        image: "https://c.ndtvimg.com/french-fries_625x300_1528454061766.jpg",
        name: "French Fries",
        price: "60rs",
        category: "Evening",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit, dignissimos.",
    },
];

export default Menu;